#!/usr/bin/env bash
set -euo pipefail

# Common flags
FLAGS=(
  -c opt
  --define=MEDIAPIPE_DISABLE_GPU=0
  --copt=-DMESA_EGL_NO_X11_HEADERS
  --copt=-DEGL_NO_X11
  --build_tag_filters=-ios,-apple,-swift,-android,-metal,-objc,-java
)

TARGETS=(
  //mediapipe_custom/...
)

EXCLUDES=(
  -//mediapipe_custom/examples/... 
  -//mediapipe_custom/tasks/ios/... 
  -//mediapipe_custom/examples/android/... 
  -//mediapipe_custom/gpu:gl_ios_test 
  -//mediapipe_custom/gpu:gl_ios_test.__internal__.__test_bundle 
  -//mediapipe_custom/tasks/java/... 
  -//mediapipe_custom/tasks/python/genai/... 
  -//mediapipe_custom/tasks/python/audio/... 
  -//mediapipe_custom/gpu:gl_ios_test_lib 
  -//mediapipe_custom/calculators/image/... 
  -//mediapipe_custom/calculators/audio/... 
  -//mediapipe_custom/calculators/video/... 
  -//mediapipe_custom/calculators/core/... 
  -//mediapipe_custom/calculators/internal/... 
  -//mediapipe_custom/calculators/tensor/... 
  -//mediapipe_custom/calculators/tensorflow/... 
  -//mediapipe_custom/calculators/tflite/... 
  -//mediapipe_custom/calculators/util/... 
  -//mediapipe_custom/framework/api2/... 
  -//mediapipe_custom/framework/api3/... 
  -//mediapipe_custom/framework/debug/... 
  -//mediapipe_custom/framework/deps/... 
  -//mediapipe_custom/framework/formats/... 
  -//mediapipe_custom/framework/port/... 
  -//mediapipe_custom/framework/profiler/... 
  -//mediapipe_custom/framework/stream_handler/... 
  -//mediapipe_custom/framework/testdata/... 
  -//mediapipe_custom/framework/tool/... 
  -//mediapipe_custom/framework:calculator_profile_java_proto 
  -//mediapipe_custom/framework:calculator_contract_test_java_proto 
  -//mediapipe_custom/framework:packet_generator_java_proto 
  -//mediapipe_custom/framework:graph_runtime_info_java_proto 
  -//mediapipe_custom/framework:calculator_options_java_proto 
  -//mediapipe_custom/framework:calculator_contract_test_java_proto_lite 
  -//mediapipe_custom/framework:status_handler_java_proto_lite 
  -//mediapipe_custom/framework:calculator_options_java_proto_lite 
  -//mediapipe_custom/framework:graph_runtime_info_java_proto_lite 
  -//mediapipe_custom/framework:packet_test_java_proto_lite 
  -//mediapipe_custom/framework:mediapipe_options_java_proto_lite 
  -//mediapipe_custom/framework:mediapipe_options_java_proto 
  -//mediapipe_custom/framework:calculator_profile_java_proto_lite 
  -//mediapipe_custom/gpu:metal 
  -//mediapipe_custom/gpu:metal_copy_calculator 
  -//mediapipe_custom/gpu:metal_rgb_weight_calculator
  -//mediapipe_custom/gpu:metal_shared_resources
  -//mediapipe_custom/gpu:metal_sobel_calculator
  -//mediapipe_custom/gpu:metal_sobel_compute_calculator
)

echo ">>> Building (filtered) MediaPipe custom..."
bazel build "${FLAGS[@]}" -- "${TARGETS[@]}" "${EXCLUDES[@]}"
